[general]
name = "SUNShINE"
url = "https://sunshine.acme.universe"
logo = "https://sunshine.acme.universe/static/media/Sunshine-Logo-FB1200x627.c038d9ef.png"
allowed_origins = ["*"]
port = 8000

[paths]
uploads = "./uploads"
latex = "./contract/tex"
migrations = "./models/migrations"

[session]
auth = "C1EOc3fJNxaVOT34snTBpA6iJyrWMWnlsTApj1V3Uv4yD1/kHmkoRrIz0sitO9RBTBhvqGEfQ0TtXexm88EpRQ=="
encr = "dKdJdGfduc2gEyvl2h0mRSUbYDr+TJMrnSkP0S7qZlg="
path = "/"
http_only = false

[mail]
backend = "file"
from = "SUNShINE <admin@sunshine.acme.universe>"
host = "/tmp/sunshine/mails"
