apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-nfs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 9Gi
  storageClassName: nfs
