-- +goose Up
CREATE TABLE onboarding_user_data (
    id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
    session CHARACTER VARYING(255) NOT NULL,
    lang CHARACTER VARYING(255) NOT NULL,
    ip CHARACTER VARYING(255) NOT NULL,
    menu_type CHARACTER VARYING(255) NOT NULL,
    post_code CHARACTER VARYING(255) NOT NULL,
    oss_admin_id CHARACTER VARYING(255) NOT NULL,
    user_id CHARACTER VARYING(255) NOT NULL,
    name CHARACTER VARYING(255) NOT NULL,
    surname CHARACTER VARYING(255) NOT NULL,
    email CHARACTER VARYING(255) NOT NULL,
    password CHARACTER VARYING(255) NOT NULL,
    phone_number  CHARACTER VARYING(255) NOT NULL,
    city CHARACTER VARYING(255) NOT NULL,
    country CHARACTER VARYING(255) NOT NULL,
    org_type CHARACTER VARYING(255) NOT NULL,
    org_name CHARACTER VARYING(255) NOT NULL,
    reg_number CHARACTER VARYING(255) NOT NULL,
    vat_number CHARACTER VARYING(255) NOT NULL,
    legal_rep_org CHARACTER VARYING(255) NOT NULL,
    website CHARACTER VARYING(255) NOT NULL,
    address CHARACTER VARYING(255) NOT NULL,
    reg_date TIMESTAMP WITH TIME ZONE,
    
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE
);


-- +goose Down
DROP TABLE onboarding_user_data;


