-- +goose Up
CREATE TABLE book_a_call (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
    name CHARACTER VARYING(255) NOT NULL,
	last_name CHARACTER VARYING(255) NOT NULL,
	email CHARACTER VARYING(127) NOT NULL,
    phone_number CHARACTER VARYING(255) NOT NULL,
	oss_admin_id CHARACTER VARYING(255) NOT NULL,
	menu_type CHARACTER VARYING(255) NOT NULL,
	description CHARACTER VARYING(255)NOT NULL,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE book_a_call;


