-- +goose Up
CREATE TABLE send_mail (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
    name CHARACTER VARYING(255) NOT NULL,
	email CHARACTER VARYING(255) NOT NULL,
	subject CHARACTER VARYING(255) NOT NULL,
    details CHARACTER VARYING(255) NOT NULL,
    pdf_file TEXT NOT NULL,
    
	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE send_mail;


