-- +goose Up
CREATE TABLE placeholder (
	id UUID PRIMARY KEY DEFAULT PUBLIC.gen_random_uuid(),
    index INTEGER NOT NULL,
	name CHARACTER VARYING(255)NOT NULL,
	require BOOLEAN DEFAULT false,
	menu_type CHARACTER VARYING(255) NOT NULL,
	oss_admin_id CHARACTER VARYING(255) NOT NULL,
	default_score INTEGER NOT NULL,
	placeholder CHARACTER VARYING(255)NOT NULL,
	input_type CHARACTER VARYING(255)NOT NULL,
	title CHARACTER VARYING(255)NOT NULL,
	option_value CHARACTER VARYING(255)NOT NULL,
	image CHARACTER VARYING(255)NOT NULL,
	lang CHARACTER VARYING(255) NOT NULL,

	created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
	deleted_at TIMESTAMP WITH TIME ZONE
);

-- +goose Down
DROP TABLE placeholder;


